#!/usr/bin/env python3
"""
convert_md_to_xlsx.py

Convert markdown test case file (generated by Cowork) to xlsx format
matching Ticketbox Google Sheets template.

Usage:
    python convert_md_to_xlsx.py input.md [output.xlsx]

Examples:
    python convert_md_to_xlsx.py AboutArtist.md
    python convert_md_to_xlsx.py AboutArtist.md MyTestCases.xlsx

Requirements:
    pip install openpyxl
"""

import sys
import re
from pathlib import Path

try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter
except ImportError:
    print("ERROR: openpyxl not installed. Run: pip install openpyxl")
    sys.exit(1)


# ============================================================
# STYLE CONFIGURATION
# ============================================================

HEADER_FILL = PatternFill('solid', start_color='0B4F2B')   # Xanh đậm - header row
SECTION_FILL = PatternFill('solid', start_color='D9EAD3')  # Xanh nhạt - section row
PRIORITY_FILLS = {
    "High":   PatternFill('solid', start_color='F4CCCC'),  # đỏ nhạt
    "Medium": PatternFill('solid', start_color='FFF2CC'),  # vàng nhạt
    "Low":    PatternFill('solid', start_color='D9EAD3'),  # xanh nhạt
}

HEADER_FONT  = Font(name='Arial', bold=True, color='FFFFFF', size=11)
SECTION_FONT = Font(name='Arial', bold=True, color='000000', size=11)
NORMAL_FONT  = Font(name='Arial', size=10)
DESC_FONT    = Font(name='Arial', italic=True, color='1F7A1F', size=10)

THIN_BORDER = Border(
    left=Side(style='thin', color='CCCCCC'),
    right=Side(style='thin', color='CCCCCC'),
    top=Side(style='thin', color='CCCCCC'),
    bottom=Side(style='thin', color='CCCCCC'),
)

WRAP_ALIGN   = Alignment(wrap_text=True, vertical='top', horizontal='left')
CENTER_ALIGN = Alignment(wrap_text=True, vertical='center', horizontal='center')

HEADERS = [
    "ID",
    "Test Case Description",
    "Category",
    "Pre-condition / Test Data",
    "Test Step",
    "Expected Result",
    "Priority",
    "Test Result Round 1 (dd/mm/yyyy)",
    "Test Result on PROD env (dd/mm/yyyy)",
    "Note",
]

COL_WIDTHS = {
    1: 10,   # ID
    2: 45,   # Description
    3: 25,   # Category
    4: 40,   # Pre-condition / Test Data
    5: 50,   # Test Step
    6: 50,   # Expected Result
    7: 10,   # Priority
    8: 20,   # Test Result Round 1
    9: 22,   # Test Result PROD
    10: 35,  # Note
}


# ============================================================
# MARKDOWN PARSING
# ============================================================

def parse_markdown_tables(md_content: str):
    """
    Parse markdown content and extract test case rows from tables.
    Only processes tables that are TEST CASE tables (have ID + Description columns).
    Skips Coverage Summary, Questions to PO/BA, and other tables.
    Returns a list of rows, each row is a list of 10 values.
    """
    lines = md_content.split('\n')
    rows = []
    in_table = False
    table_lines = []

    for line in lines:
        stripped = line.strip()
        if stripped.startswith('|') and stripped.endswith('|'):
            table_lines.append(stripped)
            in_table = True
        else:
            if in_table and table_lines:
                # Only process if this is a TEST CASE table
                if _is_test_case_table(table_lines):
                    rows.extend(_process_table_block(table_lines))
                table_lines = []
            in_table = False

    # Process the last table if file ends with one
    if in_table and table_lines:
        if _is_test_case_table(table_lines):
            rows.extend(_process_table_block(table_lines))

    return rows


def _is_test_case_table(lines: list) -> bool:
    """
    Check if a markdown table is a TEST CASE table.
    Test case tables have a header row with 'ID' as first column
    and a Description-like column as second.
    """
    for line in lines:
        cells = _split_md_row(line)
        if _is_markdown_table_header(cells):
            return True
        # Skip separator lines, keep checking
        if all(re.match(r'^:?-+:?$', c) for c in cells if c):
            continue
        # If we hit a non-header data row before finding the header, it's not a TC table
        # (but actually markdown table always has header first, so this shouldn't happen)
    return False


def _process_table_block(lines: list):
    """
    Process a block of markdown table lines.
    Skip header rows (contain column names like 'ID', 'Test Case Description').
    Skip separator rows (contain '---').
    Return only actual data rows (test cases and section headers).

    Note: A TC row may contain a NESTED markdown table embedded in a cell
    (vd: Test Data có bảng mapping VI/EN). When this happens, MD parsing
    splits the nested table pipes into extra cells. We need to detect this
    and merge extra cells back into the preceding content cell.
    """
    # Detect main table column count from header
    main_col_count = None
    for line in lines:
        cells = _split_md_row(line)
        if _is_markdown_table_header(cells):
            main_col_count = len(cells)
            break

    if main_col_count is None:
        main_col_count = 10  # Fallback

    data_rows = []
    for line in lines:
        cells = _split_md_row(line)

        # Skip separator rows
        if all(re.match(r'^:?-+:?$', c) for c in cells if c):
            continue

        # Skip markdown table header rows
        if _is_markdown_table_header(cells):
            continue

        if len(cells) < 3:
            continue

        # Handle nested tables: if row has MORE cells than main table,
        # it's because a cell contains "|" characters (from nested table).
        # Merge extra cells back into the Pre-condition/Test Data column (position 4, index 3)
        # which is the column most commonly used for embedded mapping tables.
        if len(cells) > main_col_count:
            excess = len(cells) - main_col_count
            # Merge the excess cells into position 3 (Pre-condition / Test Data)
            # by joining them with " | " separator
            merge_start = 3
            merge_end = merge_start + excess + 1  # +1 because we merge INTO position merge_start
            merged = ' | '.join(cells[merge_start:merge_end])
            cells = cells[:merge_start] + [merged] + cells[merge_end:]

        # Section header row: ID == "---"
        is_section = cells[0].strip() == '---' and len(cells) > 1 and cells[1].strip() not in ('', '---')

        # Normalize cells
        cells = [_normalize_cell(c) for c in cells]

        if is_section:
            # Section header row: fill with "---" for main content columns,
            # but leave Test Result columns (8, 9) and Note (10) EMPTY
            # Main content columns are 1-7 (ID, Desc, Cat, Pre, Step, Exp, Pri)
            while len(cells) < 7:
                cells.append('---')
            cells = cells[:7]
            cells += ['', '', '']  # 3 empty columns at end
        else:
            # Normal TC row
            # If MD table has 8 columns (last one is Note), shift Note to column 10
            if len(cells) == 8:
                note_val = cells[7]
                cells = cells[:7] + ['', '', note_val]
            elif len(cells) == 9:
                note_val = cells[8]
                cells = cells[:7] + ['', '', note_val]
            else:
                while len(cells) < 10:
                    cells.append('')

        cells = cells[:10]
        data_rows.append(cells)

    return data_rows


def _split_md_row(line: str) -> list:
    """Split a markdown table row by | and return clean cell list."""
    line = line.strip()
    if not (line.startswith('|') and line.endswith('|')):
        return []
    cells = [c.strip() for c in line.split('|')]
    # Remove empty cells at start/end (from leading/trailing |)
    if cells and cells[0] == '':
        cells = cells[1:]
    if cells and cells[-1] == '':
        cells = cells[:-1]
    return cells


def _is_markdown_table_header(cells: list) -> bool:
    """Check if a row is the markdown table header (column names like ID, Description...)."""
    if not cells:
        return False
    first = cells[0].lower().strip()
    # Strict match: first cell must be exactly "id" or "#"
    if first in ('id', '#'):
        # And second cell should contain "description" or "test case"
        if len(cells) > 1:
            second = cells[1].lower()
            if 'description' in second or 'test case' in second:
                return True
    return False


def _normalize_cell(content: str) -> str:
    """Convert markdown-specific syntax to plain text for xlsx."""
    # Replace <br> and <br/> with newlines
    content = re.sub(r'<br\s*/?>', '\n', content, flags=re.IGNORECASE)
    # Remove bold/italic markers that don't render in plain cells
    content = content.replace('**', '')
    # Decode HTML entities (common ones)
    content = (content
               .replace('&lt;', '<')
               .replace('&gt;', '>')
               .replace('&amp;', '&')
               .replace('&quot;', '"')
               .replace('&#39;', "'"))
    return content.strip()


def is_section_header_row(row: list) -> bool:
    """Check if a row is a section header (ID = '---' and has a title in Description)."""
    if not row:
        return False
    return row[0].strip() == '---' and row[1].strip() not in ('', '---')


# ============================================================
# XLSX GENERATION
# ============================================================

def write_xlsx(rows: list, output_path: str, sheet_name: str = "Test Cases"):
    """Write parsed rows to xlsx file with Ticketbox styling."""
    wb = Workbook()
    ws = wb.active
    ws.title = sheet_name[:31]  # Excel sheet name max 31 chars

    # Write header row
    for col_idx, header in enumerate(HEADERS, start=1):
        cell = ws.cell(row=1, column=col_idx, value=header)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = CENTER_ALIGN
        cell.border = THIN_BORDER

    ws.freeze_panes = 'A2'

    # Write data rows
    for row_idx, row_data in enumerate(rows, start=2):
        is_section = is_section_header_row(row_data)

        for col_idx, value in enumerate(row_data, start=1):
            cell = ws.cell(row=row_idx, column=col_idx, value=value)
            cell.border = THIN_BORDER
            cell.alignment = WRAP_ALIGN

            if is_section:
                cell.fill = SECTION_FILL
                cell.font = SECTION_FONT
            else:
                # Description column italic green
                if col_idx == 2:
                    cell.font = DESC_FONT
                else:
                    cell.font = NORMAL_FONT

                # Priority column coloring + center align
                if col_idx == 7 and value in PRIORITY_FILLS:
                    cell.fill = PRIORITY_FILLS[value]
                    cell.alignment = CENTER_ALIGN

    # Set column widths
    for col_idx, width in COL_WIDTHS.items():
        ws.column_dimensions[get_column_letter(col_idx)].width = width

    # Header row height
    ws.row_dimensions[1].height = 35

    wb.save(output_path)


# ============================================================
# MAIN
# ============================================================

def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    input_path = Path(sys.argv[1])
    if not input_path.exists():
        print(f"ERROR: File not found: {input_path}")
        sys.exit(1)

    if not input_path.suffix.lower() == '.md':
        print(f"WARNING: Input file doesn't have .md extension: {input_path}")

    # Output path
    if len(sys.argv) >= 3:
        output_path = Path(sys.argv[2])
    else:
        output_path = input_path.with_suffix('.xlsx')

    # Sheet name = file stem (without extension)
    sheet_name = input_path.stem

    # Read markdown
    md_content = input_path.read_text(encoding='utf-8')

    # Parse tables
    rows = parse_markdown_tables(md_content)

    if not rows:
        print("ERROR: No test case rows found in markdown file.")
        print("Make sure the markdown contains tables with ID/Description columns.")
        sys.exit(1)

    # Count statistics
    total = len(rows)
    sections = sum(1 for r in rows if is_section_header_row(r))
    test_cases = total - sections

    # Write xlsx
    write_xlsx(rows, str(output_path), sheet_name=sheet_name)

    print(f"✅ Success!")
    print(f"   Input:  {input_path}")
    print(f"   Output: {output_path}")
    print(f"   Stats:  {test_cases} test cases + {sections} section headers = {total} rows")


if __name__ == '__main__':
    main()